name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # required to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up Node.js + npm cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # 3) Install dependencies and generate (instead of build)
      - name: Install dependencies and generate
        run: |
          npm ci
          npm run generate

      # 4) Deploy to GitHub Pages (gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          # optional: customize commit message
          commit_message: "Deploy: ${{ github.sha }}"
